# Generated by Django 4.2.21 on 2025-05-23 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('orders_assigned', models.IntegerField()),
                ('total_distance', models.FloatField()),
                ('total_time', models.IntegerField()),
                ('earnings', models.FloatField()),
                ('compliance_flag', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='agents.agent')),
            ],
        ),
    ]
