# Generated by Django 4.2.21 on 2025-05-23 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('max_working_hours', models.FloatField(default=10.0)),
                ('max_distance_per_day', models.FloatField(default=100.0)),
                ('is_active', models.BooleanField(default=False)),
                ('available_for_assignment', models.BooleanField(default=False)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='warehouses.warehouse')),
            ],
        ),
    ]
